### ISSUE TITLE
slackbot: considerations for moving to heroku

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/dockerfiles#69]
@aric49: you may want to really consider *not* putting slackbot on heroku for the issues/recommendations outlined in this slackbot issue: https://github.com/ekmartin/slack-irc/issues/12#issuecomment-84958867

just wanted to make you aware of this.

**Comment by aric49** [comment]
Got it.   Yeah, we definitely don't want to cause any necessary spam due to the Heroku services restarting periodically...  I'll do some research and see if there are any other hosted container solutions we can leverage for free.

**Comment by wilkers-steve** [comment]
@v1k0d3n @aric49 yep.  This is part of the reason why I haven't been working on this lately.  Heroku's really cool for integrations not used often enough (like the meme-bot :(), but for something as integral as the slackbot, a different approach is the best case.  I can help look for alternatives if necessary @aric49

**Comment by v1k0d3n** [comment]
good reason to find and potentially fund an outside cloud space like AWS/Azure.

i can run with this item.

**Comment by wilkers-steve** [comment]
@v1k0d3n sounds good 👍

**Comment by v1k0d3n** [comment]
@wilkers-steve and @aric49 where is slackbot currently? can we document this somewhere internally by chance?

**Comment by v1k0d3n** [comment]
@aric49 never really heard back from you guys. now that we're moving to ATL, do you think this is a good place for it? if it is, we really need it documented, as with the rest of our lab items.
