### ISSUE TITLE
No kube-controller-manager image for k8s 1.5.2 available on quay.io

### ISSUE THREAD

**Issue by intlabs** [att-comdev/dockerfiles#77]
There is no controller-manager image with ceph rbd on quay.io for K8s 1.5.2, this means that halcyon cannot be used with this version of K8s.

A few external projects to AT&T use this version of K8s, eg Kolla-Kubernetes, so it would be great if we could provide an image to the community in support of these projects.

**Comment by v1k0d3n** [comment]
done.
