### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by TechauraIO** [att-comdev/dockerfiles#91]
Any chance we could get a prebuilt image on quay for ARM and ARM64?   We'd rather you control it vs. us forking and building one.

**Comment by intlabs** [comment]
@pingthings Which image would you be looking for? Some may be pretty easy to get built for ARMx but others could be a little trickier. This recent merge (https://github.com/docker/docker/pull/31352) should make supporting multiple arches much easier when it hits the distro packages.

**Comment by TechauraIO** [comment]
Specifically kube-controller-manager with the CEPH tools install… so that
we can add image: to our kube-controller-manager.yaml manifest.  Our team
is stretched to the hilt and it looks like you guys have the same need we
do with Kubernetes and Ceph.   We’d really owe you regarding an ARM build.
